MyMusicWebApplication/Controllers/AddController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyMusicWebApplication.Models;

namespace MyMusicWebApplication.Controllers
{
    public class AddController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        MusicAlbumDbAccessLayer madb = new MusicAlbumDbAccessLayer();

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveMusicAlbum([Bind] MusicAlbum musicAlbum)
        {
            string resp = madb.AddMusicAlbum(musicAlbum);
            TempData["msg"] = resp;
            
            return View();
        }
    }

}

MyMusicWebApplication/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyMusicWebApplication.Controllers
{
    public class ContactController: Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyMusicWebApplication/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/3.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/4.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/6.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

MyMusicWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
<div class="container">

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="ShoppingCart" asp-action="Index">Shopping Cart</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                    <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                    <li><a asp-controller="Add" asp-action="Index">Add Music Album</a></li>
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="col-md-3">
            <p class="lead">
                <img class="img-responsive" alt="My Music Album Shop'" src="~/Images/1.jpg" />
            </p>
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>
@RenderSection("Scripts", required: false)
</body>
</html>

MyMusicWebApplication/Views/Shared/_MusicAlbumCard.cshtml
@model MusicAlbum

<div class="col-sm-3 col-lg-3 col-md-3">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h4><a asp-controller="MusicAlbum" asp-action="Details" asp-route-id="@Model.MusicAlbumId">@Model.Name</a></h4>
            <p><h5>@Model.ShortDescription</h5></p>
        </div>
        
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-musicAlbumId="@Model.MusicAlbumId">@Model.Price.ToString("c")</a>
            </p>
        </div>
    </div>
</div>